name: MacOS

on:
  push:

env:
  C_FLAGS: '-Isrc -std=c99'
  CPP_FLAGS: '-Isrc -std=c++14'
  CUDA_FLAGS: '-Isrc -std=c++14'

jobs:

  cpp_cpu:
    name: C++ (CPU)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: compile backend
        run: |
          clang++ -c src/core.cpp $CPP_FLAGS -o core.o
          clang++ -c src/alts.cpp $CPP_FLAGS -o alts.o

      - name: compile and link main
        run: |
          clang++ main.cpp core.o alts.o $CPP_FLAGS -o main

      - name: run main
        run: |
          ./main

  c_cpu:
    name: C (CPU)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: compile backend
        run: |
          clang++ -c src/core.cpp $CPP_FLAGS -o core.o
          clang++ -c src/alts.cpp $CPP_FLAGS -o alts.o

      - name: compile and link main
        run: |
          clang main.c core.o alts.o $C_FLAGS -o main

      - name: run main
        run: |
          ./main