name: Windows

on:
  push:

env:
  C_FLAGS: '-Isrc -std=c99'
  CPP_FLAGS: '-Isrc -std=c++14'
  CUDA_FLAGS: '-Isrc -std=c++14'

jobs:

  cpp_cpu:
    name: C++ (CPU)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: compile backend
        shell: cmd
        run: |
          cl -c src/core.cpp $CPP_FLAGS
          cl -c src/alts.cpp $CPP_FLAGS

      - name: compile and link main
        shell: cmd
        run: |
          cl main.cpp core.obj alts.obj $CPP_FLAGS

      - name: run main
        shell: cmd
        run: |
          main.exe

  cpp_gpu:
    name: C++ (GPU)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.14
        with: 
          sub-packages: '["nvcc"]'
          method: 'network'

      - name: compile backend
        shell: cmd
        run: |
          nvcc -c src/core.cu $CUDA_FLAGS
          cl -c src/alts.cpp $CPP_FLAG

      - name: compile main
        shell: cmd
        run: |
          cl -c main.cpp $CPP_FLAGS

      - name: link
        shell: cmd
        run: |
          nvcc main.obj core.obj alts.obj $CUDA_FLAGS

  c_cpu:
    name: C (CPU)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: compile backend
        shell: cmd
        run: |
          cl -c src/core.cpp $CPP_FLAGS
          cl -c src/alts.cpp $CPP_FLAGS

      - name: compile and link main
        shell: cmd
        run: |
          cl main.c core.obj alts.obj $C_FLAGS

      - name: run main
        shell: cmd
        run: |
          main.exe

  c_gpu:
    name: C (GPU)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.14
        with: 
          sub-packages: '["nvcc"]'
          method: 'network'

      - name: compile backend
        shell: cmd
        run: |
          nvcc -c src/core.cu $CUDA_FLAGS
          cl -c src/alts.cpp $CPP_FLAGS

      - name: compile main
        shell: cmd
        run: |
          cl -c main.c $CPP_FLAGS

      - name: link
        shell: cmd
        run: |
          nvcc main.obj core.obj alts.obj $CUDA_FLSGS -o main